project:
  type: book
  output-dir: docs/correction #changer display dans css et \solnfalse dnas preamble.tex pour les corrections 
  
book:
  sidebar: 
    style: docked 
    search: true
    background: primary
#    title: "L. Rouvière"
#    collapse-level: 3
  title: "Statistique en grande dimension"
  author: "L. Rouvière"
  date: today
  date-format: long
  site-path: "/TUTO_GRANDE_DIM/"
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
#    - background: light
#    - title: "Visu"
#    - contents: 
#      - index.qmd
#      - intro.qmd
  page-navigation: true
  chapters:
    - index.qmd
    - part: "Supervisée"
      chapters:
        - 01-intro-grande-dim.qmd
        - 02-reg-comp.qmd
        - 03-ridge-lasso.qmd
        - 04-mod-add.qmd
    - part: "Non supevisée"
      chapters:
        - 05-kmeans-cah.qmd
    - references.qmd

bibliography: references.bib

format: 
  html:
    theme: cosmo #cosmo
    highlight-style: github
    css: style.css
#    code-block-background: false
    code-block-bg: true
    code-block-border-left: "#31BAE9"
    backgroundcolor: LightYellow
    toc: true
#    code-tools: true
  pdf:
    documentclass: scrreprt
    keep-tex: true
    pdf-engine: xelatex #pdflatex #lualatex
    highlight-style: github
    fig-height: 3.8
    fig-width: 5.2
    linkcolor: red
    urlcolor: magenta
    toccolor: red
    include-in-header: 
      - /Users/laurent//Google Drive/FICHIERS_STYLE/tuto_quarto/preamble.tex
    lang: fr
  epub: 
    keep-md: true
    toc: true
    lang: fr
    css: style.css
    highlight-style: github
#    pdf-engine: pdflatex
#    include-in-header: 
#      - preamble.tex

lang: fr
execute:
  warning: false
  echo: true
#  cache: false
#  freeze: auto

editor: visual

